// Code generated by internal/managed/gen. DO NOT EDIT.

package managed

// expected is the managed runtime payload shipped with this release,
// keyed by path relative to the svibe config root.
var expected = map[string]string{
	"config/models.yaml":               "4f98628b2914888866a4b1d49ee63085025ba9a39c6ed5ff7a86cbdf0a746c3a",
	"core/skills/sv-beads/SKILL.md":    "0328c6ae4fa8b8adb1b2752c381867ed77c5de21f500090fffc03e795906ae23",
	"core/skills/sv-execute/SKILL.md":  "f43ca3fdf3c97f370b39a51f3b3a50bdc3221791439c302bd519e07b889220c8",
	"core/skills/sv-finalize/SKILL.md": "fccf43f165c424074c60e45497b629ff54a4d2f924074b3daee9e73b236b0a84",
	"core/skills/sv-plan/SKILL.md":     "295beb6a9b56180dfefa695597880def8f7011eb1059f44bd0296cb562be698d",
	"core/skills/sv-review/SKILL.md":   "17a3579d8e0e471176dfc1625d8f2fcb1ea9c5754d24ff822ab92fd9cb69d8f5",
	"core/skills/sv-verify/SKILL.md":   "16e6c759779526f2326c3703e571cf6d87eac87c7dda2ae7afb7f4ba4c371a7e",
	"core/structured-vibe.yaml":        "4711fa90d1bbde55d198217c0e2a7a30a6f594a379dd5cf1ca7814a64fa64470",
}
